full_rebuild: true
name: DLF Metadata Assessment Working Group
author: DLF AIG Metadata Working Group
version: V 1.0
encoding: utf-8
theme: minima
markdown: kramdown
kramdown:
  input: GFM
relative_permalinks: false
collections:
  metadata_specs:
    output: true
  entries:
  institutions:
    output: true
sass:
  sass_dir: _sass
  style: :compressed
exclude: [
.git,
.gitignore,
README.md,
.sass-cache,
config.ru,
vendor,
Gemfile,
Gemfile.lock
]
defaults:
    -
        scope:
            path: ""
        values:
            layout: "default"